steps:
  - id: "build:showcase.ingress-observer"
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '.', '-f', 'ingress-observer.Dockerfile', '-t', 'gcr.io/laica-lunasys/oauth2-proxy-manager/ingress-observer']
  - id: "push:showcase.ingress-observer"
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/laica-lunasys/oauth2-proxy-manager/ingress-observer:latest']
